// <auto-generated />
using System;
using APKtest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APKtest.Migrations
{
    [DbContext(typeof(APKContextTest))]
    partial class APKContextTestModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APKtest.Models.Merilna_Naprava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Zemljepisna_Dolzina")
                        .HasColumnType("real");

                    b.Property<float>("Zempljepisna_Sirina")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Merilna_Naprava");
                });

            modelBuilder.Entity("APKtest.Models.MeritveA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum_Meritve")
                        .HasColumnType("datetime2");

                    b.Property<int>("Merilna_NapravaId")
                        .HasColumnType("int");

                    b.Property<int>("MetrologId")
                        .HasColumnType("int");

                    b.Property<string>("Okvara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Temperatura")
                        .HasColumnType("real");

                    b.Property<float>("Vlažnost")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Merilna_NapravaId");

                    b.HasIndex("MetrologId");

                    b.ToTable("Meritve");
                });

            modelBuilder.Entity("APKtest.Models.Metrolog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum_Zaposlitve")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Metrolog");
                });

            modelBuilder.Entity("APKtest.Models.MeritveA", b =>
                {
                    b.HasOne("APKtest.Models.Merilna_Naprava", "Merilna_Naprava")
                        .WithMany("MeritveA")
                        .HasForeignKey("Merilna_NapravaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APKtest.Models.Metrolog", "Metrolog")
                        .WithMany("Meritve")
                        .HasForeignKey("MetrologId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merilna_Naprava");

                    b.Navigation("Metrolog");
                });

            modelBuilder.Entity("APKtest.Models.Merilna_Naprava", b =>
                {
                    b.Navigation("MeritveA");
                });

            modelBuilder.Entity("APKtest.Models.Metrolog", b =>
                {
                    b.Navigation("Meritve");
                });
#pragma warning restore 612, 618
        }
    }
}
